In [13]:
import numpy as np
from numpy.matlib import zeros
from soupsieve.css_match import DAYS_IN_WEEK

In [100]:
days =  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

the = np.array(days)
print(the)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [101]:
#The zeros_like() make enable you to be able to create arrays of zeros like a varriable you alredy have no need of to worry about the lenght expetialy when you are working with large data set

zeros_array = np.zeros_like(the)
print(zeros_array)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [102]:
#Array of onces
once_array = np.ones_like(the)
print(once_array)

once_array = np.ones(5)
print(once_array)


[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1. 1. 1. 1. 1.]


In [103]:
range_array = np.arange(0, len(the))
print(range_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [104]:
random_array = np.random.randint(2, len(range_array), len(range_array))
print(random_array)

[ 4 11 12 11  2  3  2  2 13  5  9  4 13  4  5]


In [105]:
# 2 dimemesionnal array
mutple_array = np.array ([[1,2,3,4],
                [5,6,7,8],])
print(mutple_array)

[[1 2 3 4]
 [5 6 7 8]]


In [106]:
eye  = np.eye(7)
print(eye)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [107]:
zeros_array = np.random.randint(0, 9, 3)
print(zeros_array)


[7 6 1]


In [108]:
anothrlike = np.zeros_like(eye)
print(anothrlike)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [109]:
arrange = np.arange(1, 90 ,1)
print(arrange)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]


In [110]:
once = np.ones([3,3])
once [1 , 1] = 0
print(once)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [111]:
we = np.ones([7])
print(we)

[1. 1. 1. 1. 1. 1. 1.]


In [112]:
a = np.array([[1,2,3,4], [5,6,7,8]])
b = np.array([[9,2,8,4], [3,6,8,2]])
print(a*a)

[[ 1  4  9 16]
 [25 36 49 64]]


In [119]:
print(np.dot(a,b.T))
result = np.subtract(a,b)
print(result)

[[ 53  47]
 [145 123]]
[[-8  0 -5  0]
 [ 2  0 -1  6]]


In [7]:

a = np.array([[1,2,3,4], [5,6,7,8]])
b = np.array([[9,2,8,4], [3,6,8,2]])

print("Dot product (a · b.T):")
print(np.dot(a, b.T))  # shape (2, 2)

print("\nElement-wise subtraction:")
result = np.subtract(a, b)
print(result)


Dot product (a · b.T):
[[ 53  47]
 [145 123]]

Element-wise subtraction:
[[-8  0 -5  0]
 [ 2  0 -1  6]]


In [6]:
ok = np.array([0, 2, 3], dtype=np.bool_)
print(ok)

[False  True  True]


In [7]:
a = np.array([[1, 2], [3, 4]])
print(a[0, 1])

2


In [8]:
a = np.array([10, 20, 30])

b = np.array([[1], [2], [3]])

print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [14]:
x = np.array([10, 20, 30])

y = x * 2
print(y)

[20 40 60]


In [17]:
A = np.random.rand(5, 3, 4)

B = np.random.rand(5, 4, 2)
print(np.dot(A, B,).shape)

(5, 3, 5, 2)


In [18]:
A = np.array([[1, 2, 3]])

B = np.array([[4], [5], [6]])

print(A @ B)

[[32]]


In [20]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

x = np.arange(6)
windowed = sliding_window_view(a, window_shape=3)

v = sliding_window_view(x, 3)
print(v)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [23]:
A = np.ones((2, 3))
print(A)
B = np.ones((3,))
print(B)

C = A @ B
print(C.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1.]
(2,)


In [31]:
A = np.array([[1, 2],

               [3, 4]])

B = np.array([[5, 6],

               [7, 8]])

print(A @ B)
print(np.dot(A, B))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [28]:
a=np.linspace(10, 20, 6).astype(np.float32)
print(a)

[10. 12. 14. 16. 18. 20.]


In [29]:
a= np.random.randint(0, 10, 2)
print(a)

[1 9]


In [37]:
nummbers = np.arange(25).reshape(5, 5)
print(nummbers)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [42]:
boos = (nummbers >  5) & (nummbers < 22)
print("\n", boos)


 [[False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True False False False]]


Indexing Along Mutipl DImensions

In [43]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6],])

print(arr_2d)
print(arr_2d.shape)
print("\n", arr_2d[0, 1])
print("\n", arr_2d[0, 0])
print("\n", arr_2d[0, -1])
print("\n", arr_2d[-1, 0])
print("\n", arr_2d[:, 1])

[[1 2 3]
 [4 5 6]]
(2, 3)

 2

 1

 3

 4

 [2 5]


In [48]:
arr = np.arange(0, 100, 10 )

print("\n", arr)


 [ 0 10 20 30 40 50 60 70 80 90]


In [49]:
arr__b = arr[1: 6]
print(arr__b)

[10 20 30 40 50]


In [50]:
arr_c = arr[3:]
print(arr_c)

[30 40 50 60 70 80 90]


In [51]:
arr_c = arr[:3]
print(arr_c)

[ 0 10 20]


Slicing 3d Arrays

In [53]:
import pandas as pd

In [55]:
series_1 = pd.Series([1, 2, 3])
print(series_1)

0    1
1    2
2    3
dtype: int64


In [57]:
pd.Series(5, index=[1, 2, 3])

1    5
2    5
3    5
dtype: int64

In [61]:
pd.Series (9, index=[100, 200, 300, 400])

100    9
200    9
300    9
400    9
dtype: int64

In [64]:
population = {'Senegal': 423967, 'Cameroun': 695662, 'Mali': 141297,
             'Sudan': 170312, 'Ghana': 149995}
pd.DataFrame(population, columns=['population'])

Empty DataFrame
Columns: [population]
Index: []

In [66]:
# Create a NumPy array with mixed string and numeric data
data = np.array([['Name', 'Age', 'Height', 'Weight'],
                 ['Lenin', 30, 188, 90],
                 ['Phil', 42, 178, 76],
                 ['Claire', 40, 165, 54],
                 ['Alex', 18, 140, 46]
                 ])

# Define the file path
file_path = '/sample_data/data.csv'

# Save the array as a CSV file
np.savetxt(file_path, data, delimiter=',', fmt='%s')

FileNotFoundError: [Errno 2] No such file or directory: '/sample_data/data.csv'

In [73]:
from pandas import *
import pandas as pd

df = pd.read_csv("/Users/israelisiaka/PycharmProjects/PythonProject/sample_date/california_housing_train.csv")

In [74]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB


In [76]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [80]:
df.groupby('longitude').describe()

latitude                                                            \
             count    mean       std    min      25%     50%      75%    max   
longitude                                                                      
-124.35        1.0  40.540       NaN  40.54  40.5400  40.540  40.5400  40.54   
-124.30        2.0  41.820  0.028284  41.80  41.8100  41.820  41.8300  41.84   
-124.27        1.0  40.690       NaN  40.69  40.6900  40.690  40.6900  40.69   
-124.26        1.0  40.580       NaN  40.58  40.5800  40.580  40.5800  40.58   
-124.25        1.0  40.280       NaN  40.28  40.2800  40.280  40.2800  40.28   
...            ...     ...       ...    ...      ...     ...      ...    ...   
-114.58        2.0  33.620  0.014142  33.61  33.6150  33.620  33.6250  33.63   
-114.57        2.0  33.605  0.049497  33.57  33.5875  33.605  33.6225  33.64   
-114.56        1.0  33.690       NaN  33.69  33.6900  33.690  33.6900  33.69   
-114.47        1.0  34.400       NaN  34.40  34.4000  34.400  34.4000  34.40   
-114.31        1.0  34.190       NaN  34.19  34.1900  34.190  34.1900  34.19   

          housing_median_age        ... median_income          \
                       count  mean  ...           75%     max   
longitude                           ...                         
-124.35                  1.0  52.0  ...      3.014700  3.0147   
-124.30                  2.0  18.0  ...      2.768400  3.0313   
-124.27                  1.0  36.0  ...      2.517900  2.5179   
-124.26                  1.0  52.0  ...      2.357100  2.3571   
-124.25                  1.0  32.0  ...      1.941700  1.9417   
...                      ...   ...  ...           ...     ...   
-114.58                  2.0  27.0  ...      3.177050  3.3438   
-114.57                  2.0  17.0  ...      2.875025  3.1917   
-114.56                  1.0  17.0  ...      1.650900  1.6509   
-114.47                  1.0  19.0  ...      1.820000  1.8200   
-114.31                  1.0  15.0  ...      1.493600  1.4936   

          median_house_value                                              \
                       count      mean           std       min       25%   
longitude                                                                  
-124.35                  1.0   94600.0           NaN   94600.0   94600.0   
-124.30                  2.0   94700.0  12586.500705   85800.0   90250.0   
-124.27                  1.0   79000.0           NaN   79000.0   79000.0   
-124.26                  1.0  111400.0           NaN  111400.0  111400.0   
-124.25                  1.0   76100.0           NaN   76100.0   76100.0   
...                      ...       ...           ...       ...       ...   
-114.58                  2.0   78200.0   5939.696962   74000.0   76100.0   
-114.57                  2.0   69450.0   5586.143571   65500.0   67475.0   
-114.56                  1.0   85700.0           NaN   85700.0   85700.0   
-114.47                  1.0   80100.0           NaN   80100.0   80100.0   
-114.31                  1.0   66900.0           NaN   66900.0   66900.0   

                                         
                50%       75%       max  
longitude                                
-124.35     94600.0   94600.0   94600.0  
-124.30     94700.0   99150.0  103600.0  
-124.27     79000.0   79000.0   79000.0  
-124.26    111400.0  111400.0  111400.0  
-124.25     76100.0   76100.0   76100.0  
...             ...       ...       ...  
-114.58     78200.0   80300.0   82400.0  
-114.57     69450.0   71425.0   73400.0  
-114.56     85700.0   85700.0   85700.0  
-114.47     80100.0   80100.0   80100.0  
-114.31     66900.0   66900.0   66900.0  

[827 rows x 64 columns]

In [83]:
df.housing_median_age.max()
df.housing_median_age.min()

np.float64(1.0)

In [84]:
pip install scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 241.1 kB/s eta 0:00:0000:0100:02
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.5/36.5 MB 495.2 kB/s eta 0:00:0000:0100:03
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [scikit-learn] [scikit-learn]

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB


In [88]:
from  sklearn.model_selection import train_test_split
from  sklearn.linear_model import  LinearRegression
from  sklearn.matrics import  mean_squared_error



ModuleNotFoundError: No module named 'sklearn.matrics'